server:
  port: 8088
  contextPath: /cms

---
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.audioapp.cms.dto.*
  mapperLocations: classpath:mapper/*.xml

---
#开发配置
logging:
  level:
     com.audioapp.cms.mapper: debug
     org.thymeleaf: debug

spring:
  datasource:
    #url: jdbc:mysql://rm-wz9953149z266rk0n.mysql.rds.aliyuncs.com:3306/gks?characterEncoding=utf8&useSSL=true
    #username: gksadmin
    #password: Gaokaoshuo168
    url: jdbc:mysql://rm-8vb3oj86ge622d1p3po.mysql.zhangbei.rds.aliyuncs.com:3306/audio_app?characterEncoding=utf8&useSSL=true
    username: audioopr
    password: 1qaz!QAZ
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  #thymeleaf配置
  thymeleaf:
    cache: false
    prefix: classpath:static/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

  redis:
    #host: r-wz9f232c68e519b4.redis.rds.aliyuncs.com
    #password: Gaokaoshuo168
    host: 47.92.238.6
    password: Gaokaoshuo168
    timeout: 10000
    database: 0
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1

  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb

inipassword: abcd1234

aliyun:
  endpoint: oss-cn-zhangjiakou.aliyuncs.com
  accessKeyId: U2mQnrkbisfl2vNB
  accessKeySecret: Uhapcb7yrn6Mp4atqTQHKswueliTJb
  bucketName: bclh
  appKey: 27695158
